[package]
name = "taceo-eddsa-babyjubjub"
version = "0.6.1"
edition.workspace = true
# Higher than the workspace MSRV: `taceo-ark-serde-compat` 0.6 requires 1.90.
rust-version = "1.90"
description = "An EdDSA signature scheme implementation over the Baby Jubjub elliptic curve using Poseidon2, useful for SNARK-friendliness."
readme = "./README.md"
repository.workspace = true
license.workspace = true
publish = true

[dependencies]
ark-babyjubjub = { package = "taceo-ark-babyjubjub", path = "../ark-babyjubjub", version = "0.6.0" }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serde-compat = { workspace = true }
ark-serialize = { workspace = true }
blake3 = { workspace = true }
eyre = { workspace = true }
num-bigint.workspace = true
poseidon2 = { package = "taceo-poseidon2", path = "../poseidon2", version = "0.3.0", default-features = false, features = [
  "bn254",
  "t8"
] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
zeroize = { workspace = true }

[lints]
workspace = true
